#!/bin/ash

# System Startup Script
# 


mkdir -p /run
mount -n /run
mkdir -p /run/{var,lock,shm}
chmod 1777 /run/shm

/bin/mount -n -o nosuid,noexec,nodev /proc
/bin/mount -n -o nosuid,noexec,nodev /sys
/bin/mount -n -o mode=0755,nosuid /dev
/bin/mount -t tmpfs /tmp /tmp
/bin/mount -t tmpfs -o mode=0755 none /dev

/bin/mkdir /dev/pts
ln -s /run/shm /dev/shm

/bin/mount -t tmpfs -o mode=0755 /var /var

for x in cache lib lib/misc lib/locate local lock log mail opt run spool; do mkdir /var/$x; done
ln -s ../tmp /var/tmp

echo -n "Starting mdev: "
/sbin/mdev -s

echo -n "Mounting devpts: "
mount /dev/pts
check_status

if [ -x /sbin/hwclock ] && [ -e /dev/rtc ]; then
	echo -n "Setting system clock: "
	hwclock --hctosys --utc
fi

if [ -x /sbin/fsck ]; then
	echo "Starting fsck for local filesystems."
	fsck -A -C -R -T -t nonfs,nosmbfs
	if [ "$?" -gt 2 ]; then
		echo "WARNING: Errors found while checking filesystems."
		echo "You can login as root now, the system will reboot after logout."
		sulogin
		reboot
	elif [ "$?" = "2" ]; then
		echo "NOTICE: System needs to be rebooted now."
		sleep 1
		reboot
	else
		echo -n "Checking local filesystems: "
	fi
fi


if [ -x /sbin/swapon ]; then
	echo -n "Enabling swap space: "
	swapon -a
fi

echo -n "Remounting root rw: "
mount -n -o remount,rw / >/dev/null

echo -n "Setting hostname: "
echo "acrlinux">/etc/hostname
hostname acrlinux

echo -n "Cleaning up system: "
> /var/run/utmp
touch /var/log/wtmp
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0660 /var/log/messages
rm -rf /tmp/*
rm -f /var/run/*.pid

echo -n "Setting up interface lo: "
ip addr add 127.0.0.1/8 label lo dev lo
ip link set lo up

